# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


steps:
- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: 'latest'

- script: |
    helm package ./itdepends
  displayName: 'Packaging helm'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'HelmPublish'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'find . -name *.tgz'
    addSpnToEnvironment: true
    failOnStandardError: true