replicaCount: 3
containerName: itdepends-container


image:
  repository: itdepends.azurecr.io/itdepends
  tag: 62
  pullPolicy: IfNotPresent
  imagePullSecrets: itdepends-acr-pull-secret

ports:
  name: itdepends-port
  containerPort: 80

service:
  name: itdepends-service
  port: 80
  targetPort: itdepends-port
  appSelector: itdepends-app

settings:
  mongoConnectionString: default conString from helm
  mongoDatabaseName: default db name from helm
