apiVersion: v2
kind: Secret
metadata:
  name: itdepends-secret
type: Opaque
data:
  mongo__ConnectionString: {{ .Values.settings.mongoConnectionString | quote | b64enc }}
  mongo__DatabaseName: {{ .Values.settings.mongoDatabaseName | quote | b64enc }}