apiVersion: v1
kind: Secret
metadata:
  name: itdepends-secret
type: Opaque
data:
  mongo__ConnectionString: {{ .Values.settings.mongo__ConnectionString | quote | b64enc }}
  mongo__DatabaseName: {{ .Values.settings.mongo__DatabaseName | quote | b64enc }}